### ISSUE TITLE
The assignment states that two Projects are available but there is only one

### ISSUE THREAD

**Issue by mikedepetris** [dario-campagna/Bank-OCR-assignment#6]
Two github projects should be available as written in the "readme" of the repository, but I can find one single project in both classic and new projects page. @dario-campagna can you help please?

**Comment by dario-campagna** [comment]
The two projects mentioned in the README.md file are:

- https://github.com/users/dario-campagna/projects/1/views/1 ("new" GitHub Project)
- https://github.com/dario-campagna/Bank-OCR-assignment/projects/1 (classic GitHub Project)

They are listed under Projects and have the same name, they are two different projects and reference the same issues.

I can rephrase the sentence in README.md to make it more clear.

**Comment by mikedepetris** [comment]
Thanks for the clarification, I entered both projects but I wrongly assumed they where the same as they have almost the same structure and issues, now I got it.
